### ISSUE TITLE
Should `exec_interpreter` have `cfg = "exec"`?

### ISSUE THREAD

**Issue by tgeng** [jvolkman/rules_pycross#79]
At https://github.com/jvolkman/rules_pycross/blob/3a2a4c259e8f0cda39a23ac0d4828f00c70054d7/pycross/toolchain.bzl#L41-L45

The `exec_interpreter` of `pycross_hermetic_toolchain` is declared without any `cfg`. But since it's the exec interpreter, should it have `cfg = "exec"` so that Bazel can automatically transition it to use the exec configurations? Otherwise, configurable alias pass to this can result in incorrect targets right? Or am I missing something?

**Comment by jvolkman** [comment]
Maybe? I've only handed it the path to a pre-built executable (one of the rules_python built-in interpreters) so I guess it hasn't mattered. What are you passing for that label?

**Comment by tgeng** [comment]
Do you mind adding `cfg="exec"`? Or I can send a PR doing that.

**Comment by jvolkman** [comment]
Sorry, I haven't had a chance to investigate the idea yet. The way I do it currently [here](https://github.com/jvolkman/rules_pycross/blob/main/pycross/private/toolchain_helpers.bzl) is to set the `exec_interpreter` to the platform-specific repo, not by using that select you posted. But maybe `cfg = "exec"` would simplify some logic.

You can maybe consider using the auto-toolchain registration instead of doing it all manually, like [here](https://github.com/jvolkman/rules_pycross/blob/main/examples/lock_repo/WORKSPACE#L48-L51)

**Comment by jvolkman** [comment]
This change lets me greatly simplify the auto toolchain resolution. I was originally registering `len(python_versions) * len(platforms) * len(platforms)` toolchains, whereas now I can just register `len(python_versions)` toolchains. Each toolchain just lists the same interpreter target for both target and exec, letting `cfg` handle the differentiation.

I'm still suspicious about this being the correct approach though. It seems too easy.

**Comment by tgeng** [comment]
Yeah we use single toolchain with configurable alias to register most of the toolchains managed by ourselves in Pinterest and it has been working just fine. I believe you can also do that so you don't need to register len(python version) number of tool chains. Though the error message would be different. I also was curious what the pro and cons are between multiple toolchain vs alias with configurable actual other than different error messages.
